---
# tasks file for sbaerlocher.nginx

 - name: add nginx repo
   yum_repository:
     name: nginx repo
     description: nginx repo
     baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
     gpgcheck: no

- name: install nginx
  yum: name=nginx state=present
  notify:
    - start nginx
    - enabled nginx