---
# tasks file for sbaerlocher.nginx

- name: "{{ ansible_distribution | lower }} | add key"
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
  tags:
    - packages

- name: "{{ ansible_distribution | lower }} | add repository"
  yum_repository:
    name: nginx
    description: official nginx repo
    baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
    gpgcheck: false
    enabled: true
  tags:
    - packages
