---
# tasks file for sbaerlocher.nginx

- name: "{{ ansible_distribution | lower }} | add key"
  become: true
  apt_key:
    url: "http://nginx.org/keys/nginx_signing.key"
    state: present
  tags:
    - packages

- name: "{{ ansible_distribution | lower }} | add repository"
  become: true
  apt_repository:
    repo: "deb http://nginx.org/packages{{ '/mainline' if nginx_branch == 'mainline' }}/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} nginx"
    state: present
    filename: "nginx"
    update_cache: true
  tags:
    - packages
