---
# tasks file for sbaerlocher.nginx

- name: add official nginx key
  apt_key:
    url: "http://nginx.org/keys/nginx_signing.key"
    state: present
  tags:
    - packages

- name: add official nginx apt repository
  apt_repository:
    repo: "deb http://nginx.org/packages/mainline/ubuntu/ {{ ansible_distribution_release }} nginx"
    state: present
    filename: "nginx"
    update_cache: true
  tags:
    - packages
